name: Build and Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  defold:
    name: Build Defold
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        platform: [web] # removed windows/linux for faster testing web
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        key: ${{matrix.platform}}-defold-cache
        path: .defold-cache
    - uses: koenbollen/defold-action@main
      id: build
      with:
        target-platform: ${{matrix.platform}}
        defold-version: '1.9.6'
    - uses: actions/upload-artifact@v4
      with:
        name: pixel-line-${{matrix.platform}}-${{github.ref_name}}-${{github.sha}}
        path: ${{steps.build.outputs.build-path}}
        if-no-files-found: error
        overwrite: true
  deploy:
    name: Deploy Web Build
    needs: [defold]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 5
    - uses: actions/download-artifact@v4
      with:
        name: pixel-line-web-${{github.ref_name}}-${{github.sha}}
        path: dist/${{github.sha}}
    - name: Get Previous Commits
      run: |
        echo "EXCLUDE_LIST<<EOF" >> $GITHUB_ENV
        git rev-list --max-count=5 "${{ github.sha }}" | tail +2 >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - uses: koenbollen/github-pages-deploy-action@facf4aa10b1f9f39a88b1376b5e93fac5ce72be6
      with:
        folder: dist
        exclude: |
          index.html
          pr-preview/
          ${{ env.EXCLUDE_LIST }}
        force: false
