name: Notify changes to main
on:
  workflow_run:
    workflows: Build and Deploy
    branches: main
    types: completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Execute Discord Webhook
      run: |
        echo "${{ github.event.workflow_run.head_commit.message }}"
        msg="* $(echo "${{ github.event.workflow_run.head_commit.message }}" | head -n1)"
        # curl -vf -d content="$msg" -d username="Change to Playground" "${{ secrets.DISCORD_WEBHOOK }}"
