name: PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        key: web-defold-cache
        path: .defold-cache
    - uses: koenbollen/defold-action@main
      id: build
      name: Build
      if: github.event.action != 'closed'
      with:
        target-platform: web
        defold-version: '1.10.1'
    - name: Deploy preview
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: ${{steps.build.outputs.build-path}}
